name: Your Workflow Name

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  
jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
